# Generated by Django 5.1 on 2024-08-31 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="album_artist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_album",
                to="api.album",
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_artist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_genre",
                to="api.genre",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="audios",
            field=models.ManyToManyField(
                related_name="playlist_audios", to="api.audio"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
