# Generated by Django 5.1 on 2024-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_releaded_album_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="producer",
            field=models.CharField(
                help_text="Comma-separated list of producers", max_length=1024
            ),
        ),
    ]
