# Generated by Django 5.1 on 2024-09-29 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_audio_producer"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
