# Generated by Django 5.1 on 2024-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_playlist_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="audios",
            field=models.ManyToManyField(
                blank=True, related_name="playlist_audios", to="api.audio"
            ),
        ),
    ]
