# Generated by Django 5.1 on 2024-09-15 09:54

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=authentication.utils.rename_image
            ),
        ),
    ]
