# Generated by Django 5.1 on 2024-09-29 03:03

import authentication.utils
import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authentication.utils.rename_image,
                validators=[
                    authentication.validators.validate_user_image_size,
                    authentication.validators.validate_image_file_extension,
                ],
            ),
        ),
    ]
